[package]
name = "rytm-object"
version = "0.1.0"
authors = [ "Ali Somay <alisomay@runbox.com>" ]
edition = "2021"

[dependencies]
# Max 8.x SDK
median = { git = "https://github.com/Cycling74/median", rev = "168bd8e01971cb263c94c12cabc49d75c461f761" }
rytm-rs = { git = "https://github.com/alisomay/rytm-rs.git" }

error-logger-macro = { path = "../error-logger-macro" }

thiserror = "2"
lazy_static = "1.4.0"
tracing = "0.1"
parking_lot = "0.12"



